### ISSUE TITLE
changing DeliveryCostRequest weight prop accuracy

### ISSUE THREAD

**Issue by morozovalexander** [PankovAlxndr/dalli-sdk-php#1]
Здравствуйте! 
Можно ли в DeliveryCostRequest поле $weight  сделать типа float вместо int? по аналогии с полем weight в DalliSDK\Models\Order
А то получается, что теряем точность, и 0,5 кг при запросе стоимости доставки кастуются в 0 кг.

**Comment by PankovAlxndr** [comment]
@morozovalexander , здравствуйте, да, конечно, не знаю почему сразу так не сделал, спасибо.
Обновлю на ближайших выходных (25-26 мая)

**Comment by morozovalexander** [comment]
> @morozovalexander , здравствуйте, да, конечно, не знаю почему сразу так не сделал, спасибо. Обновлю на ближайших выходных (25-26 мая)

Большое спасибо! на тестах апи спокойно принимает в этом поле 0, и выдает такую же цену как за 1кг, я тоже не сразу заметил

**Comment by PankovAlxndr** [comment]
@morozovalexander , готово, минорной версией отделаться не удалось, плюс еще вылезли баги в CI, поэтому поправил зависимости, нужно ручками в composer.json установить новую мажорную третью версию

**Comment by PankovAlxndr** [comment]
@morozovalexander , готово, минорной версией отделаться не удалось, плюс еще вылезли баги в CI, поэтому поправил зависимости, нужно ручками в composer.json установить новую мажорную третью версию
